site_name: Learn Spezi
site_description: Comprehensive tutorial website for the Stanford Spezi framework - an open-source framework for rapid development of modern, interoperable digital health applications
site_url: https://learnspezi.com
site_author: Stanford Biodesign Digital Health
repo_url: https://github.com/StanfordSpezi/Spezi
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/StanfordSpezi
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/StanfordSpezi

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - git-authors

nav:
  - Home: index.md
  - Getting Started:
    - Environment Setup: getting-started/development-environment.md
    - Your First App: getting-started/your-first-app.md
  - Core Concepts:
    - Overview: core-concepts/overview.md
  - Modules:
    - Overview: modules/overview.md
    - Core Modules: modules/core-modules.md
    - Health & Wellness: modules/health-wellness.md
    - User Experience: modules/user-experience.md
    - Advanced Modules: modules/advanced-modules.md
  - Tutorials:
    - Overview: tutorials/overview.md
